version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "31337:3333"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - kong-net
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run dev

  redis:
    image: redis:7-alpine
    ports:
      - "26379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - kong-net
    restart: unless-stopped

volumes:
  redis-data:

networks:
  kong-net:
    external: true 